# Generated by Django 3.1.3 on 2021-01-08 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsRApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsrapi',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
