# Generated by Django 3.1.3 on 2021-01-14 14:19

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtfsRApi', '0002_auto_20210108_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsrapi',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='gtfsrapi',
            index=django.contrib.postgres.indexes.HashIndex(fields=['timestamp'], name='gtfsRApi_gt_timesta_af48a9_hash'),
        ),
    ]
